name: Lint and test

on:
  pull_request:
    branches: [master, main]
    types: [opened, synchronize]

jobs:
  Intall_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test